<<<<<<< HEAD
(function() {

  define(["vendor/amd/backbone"], function(Backbone) {
    return Backbone.View.extend({
      initialize: function(callbacks) {
        return this.buttonBarOptions = callbacks;
      },
      optionChosen: function(e) {
        var option;
        option = $(e.currentTarget).attr("data-option");
        return this.buttonBarOptions[option].call(this, e);
      }
    });
  });

}).call(this);
=======
// Generated by CoffeeScript 1.3.3

define(["vendor/backbone"], function(Backbone) {
  return Backbone.View.extend({
    initialize: function(callbacks) {
      return this.buttonBarOptions = callbacks;
    },
    optionChosen: function(e) {
      var option;
      option = $(e.currentTarget).attr("data-option");
      return this.buttonBarOptions[option].call(this, e);
    }
  });
});
>>>>>>> 70019ad6cebd2e9b9c2853cba260c0dda4297cde
