<<<<<<< HEAD

=======
// Generated by CoffeeScript 1.3.3
>>>>>>> 70019ad6cebd2e9b9c2853cba260c0dda4297cde
/*
@author Tantaman
*/

<<<<<<< HEAD

(function() {

  define(["./Component"], function(Component) {
    return Component.extend({
      initialize: function() {
        Component.prototype.initialize.apply(this, arguments);
        this.set("type", "TextBox");
        if (!(this.get("text") != null)) {
          return this.set("text", "Text");
        }
      },
      textWithBreaks: function() {},
      constructor: function TextBox() {
			Component.prototype.constructor.apply(this, arguments);
		}
    });
  });

}).call(this);
=======
define(["./Component"], function(Component) {
  return Component.extend({
    initialize: function() {
      Component.prototype.initialize.apply(this, arguments);
      this.set("type", "TextBox");
      if (!(this.get("text") != null)) {
        return this.set("text", "Text");
      }
    },
    textWithBreaks: function() {},
    constructor: function TextBox() {
			Component.prototype.constructor.apply(this, arguments);
		}
  });
});
>>>>>>> 70019ad6cebd2e9b9c2853cba260c0dda4297cde
