<<<<<<< HEAD
(function() {

  define(["vendor/amd/backbone"], function(Backbone) {
    return Backbone.Model.extend();
  });

}).call(this);
=======
// Generated by CoffeeScript 1.3.3

define(["vendor/backbone"], function(Backbone) {
  return Backbone.Model.extend();
});
>>>>>>> 70019ad6cebd2e9b9c2853cba260c0dda4297cde
