<<<<<<< HEAD

=======
// Generated by CoffeeScript 1.3.3
>>>>>>> 70019ad6cebd2e9b9c2853cba260c0dda4297cde
/*
@author Matt Crinklaw-Vogt
*/

<<<<<<< HEAD

(function() {

  define(["common/MapResolver"], function(MapResolver) {
    var iface, stateMap;
    stateMap = {
      editor: {
        slideEditor: {
          buttonBar: {
            fontSize: 72,
            fontFamily: "'Lato', sans-serif",
            fontColor: "grey",
            fontStyle: "",
            fontWeight: ""
          }
        }
      }
    };
    return iface = {
      get: function(key) {
        return MapResolver.resolveItem(stateMap, key);
      }
    };
  });

}).call(this);
=======
define(["common/MapResolver"], function(MapResolver) {
  var iface, stateMap;
  stateMap = {
    editor: {
      slideEditor: {
        buttonBar: {
          fontSize: 72,
          fontFamily: "'Lato', sans-serif",
          fontColor: "grey",
          fontStyle: "",
          fontWeight: ""
        }
      }
    }
  };
  return iface = {
    get: function(key) {
      return MapResolver.resolveItem(stateMap, key);
    }
  };
});
>>>>>>> 70019ad6cebd2e9b9c2853cba260c0dda4297cde
