<<<<<<< HEAD

=======
// Generated by CoffeeScript 1.3.3
>>>>>>> 70019ad6cebd2e9b9c2853cba260c0dda4297cde
/*
@author Matt Crinklaw-Vogt
*/

<<<<<<< HEAD

(function() {

  define(["./Editor"], function(Editor) {
    return Editor;
  });

}).call(this);
=======
define(["./Editor"], function(Editor) {
  return Editor;
});
>>>>>>> 70019ad6cebd2e9b9c2853cba260c0dda4297cde
